/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "byteTestWithThrift_constants.h"



const byteTestWithThriftConstants g_byteTestWithThrift_constants;

byteTestWithThriftConstants::byteTestWithThriftConstants() {
}



