/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef byteTestWithThrift_CONSTANTS_H
#define byteTestWithThrift_CONSTANTS_H

#include "byteTestWithThrift_types.h"



class byteTestWithThriftConstants {
 public:
  byteTestWithThriftConstants();

};

extern const byteTestWithThriftConstants g_byteTestWithThrift_constants;



#endif
